### ISSUE TITLE
Bug on Retrieving entries

### ISSUE THREAD

**Issue by frant4** [JexSrs/go-elsewherr#1]
Starting go-elsewherr...
Radarr configuration found
Sync operation started
Retrieving arr tags...
Found 200 tags
Retrieving entries...
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/JexSrs/go-elsewherr/src/arr.Get[...](...)
        /app/src/arr/arr.go:30
github.com/JexSrs/go-elsewherr/src/arr.(*Radarr).GetEntries(0x6dc315?)
        /app/src/arr/radarr.go:122 +0x7aa
main.Sync({0x750110, 0xc0000221c0})
        /app/src/main.go:50 +0x17b
main.main()
        /app/src/main.go:18 +0x18a

**Comment by JexSrs** [comment]
Hi @frant4, thank you very much for the issue, I have uploaded a new version that should fix the current problem. Feel free to re-open the issue if the problem has not been resolved for you!
